There are problems and -y was used without --force-yes
RUN apt-get -y --force-yes install maven3

WARNING: The following packages cannot be authenticated!
  maven3
E: There are problems and -y was used without --force-yes
ERROR: Service 'web' failed to build: The command '/bin/sh -c apt-get -y install maven3' returned a non-zero code: 100

http://imicrov.com/small-tech/linux-platform/package-management/apt-get-without-default-answering-yes